config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_scripts:
    src: scripts
    dst: ~/.scripts
  d_texmf:
    src: texmf
    dst: ~/texmf
profiles:
  pratchett:
    dotfiles:
    - f_vimrc
    - f_zshrc
    - f_tmux.conf
    - d_scripts
    - d_texmf
